# Generated by Django 4.1.7 on 2023-04-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_rename_login_logins"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="logins",
            new_name="login",
        ),
    ]
