# Generated by Django 4.1.7 on 2023-04-05 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_rename_logins_login"),
    ]

    operations = [
        migrations.RenameField(
            model_name="login",
            old_name="Password",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="login",
            old_name="Email",
            new_name="username",
        ),
        migrations.AddField(
            model_name="login",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
