# Generated by Django 4.2 on 2023-04-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_user_mobile_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
