# Generated by Django 4.2 on 2023-04-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_update_password_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
